---
- hosts: tag_Name_jenkinsServer
  user: ubuntu
  become: true

  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  tasks:
  - name:    Install prerequisites
    apt:
      name: ['apt-transport-https','ca-certificates', 'curl','software-properties-common']
      update_cache: yes
  - name:    Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg
  - name:    Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
#      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
  - name:    Install Docker
    apt:     name=docker-ce
  - service: name=docker enabled=yes state=started
  - user: name=ubuntu groups=docker
  - apt: name=python3-pip
  - shell: pip3 install --upgrade pip
  - shell: pip3 install docker

  - docker_container:
      name: inspur_jenkins
      image: "jenkinsci/blueocean:1.9.0"
      state: started
      restart: yes
      ports:
      - "8080:8080"
