---
- hosts: localhost
  vars:
    terraform_version: "0.11.9"
  become: yes
  become_user: root
  tasks:
    - name: add unzip package
      apt:
        name: unzip
    - name: download the biniary.
      get_url:
        url: https://releases.hashicorp.com/terraform/{{terraform_version}}/terraform_{{terraform_version}}_linux_amd64.zip
        dest: /tmp/terraform{{terraform_version}}.zip
    - unarchive:
       src: /tmp/terraform{{terraform_version}}.zip
       dest:  /usr/local/bin/