apiVersion: v1
kind: Service
metadata:
  name: qi
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: http2
    port: 9090
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx