apiVersion: apps/v1
kind: Deployment
metadata:
  name: andy-deployment
  labels:
    app: nginx
    owner: andy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        role: dog
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.4
        ports:
        - containerPort: 80
      - name: tomcat
        image: library/tomcat:7
        ports:
        - containerPort: 8080
